Add images
Adebayo-George/mobile-website pull request #1
Opened 2022-08-19 19:18 UTC by Adebayo-George

In this project, a mobile website was created and images were added to aid the good look of the user interface of the website.

2022-08-19 19:34 UTC, mirouhml requested changes
# REQUIRED CHANGES 🔴

Hi @Adebayo-George, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media4.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif?cid=ecf05e47n6s5huda7qh40syoppcaspe9vx68ddmxerd08owm&rid=giphy.gif&ct=g)

## Highlights

- Great job setting up the correct linters ✔️
- Highly organized and clean code ✔️ 👨🏻‍💻
- Professional documentation ✔️
- Correct workflow ✔️
- Meaningful commit messages ✔️

## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-19 19:34 UTC, mirouhml commented on index.html
> +    </header>
- [ ] Please know that the logo should be outside of the nav tag and inside of the header, kindly fix that.
- [ ] Please fix the size of the logo text and the weight, it should be similar to the one in the [Figma template design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=48%3A27):
![image](https://user-images.githubusercontent.com/20567503/185693173-ef38c7d9-4df5-4759-9562-c210df8cb9e5.png)

2022-08-19 19:34 UTC, mirouhml commented on index.html
> +            <p class="work">I'm a software developer</p>
- [ ] For this line (where it says "I'm a software developer"), it's better to use a lesser `hx` tag like `h2` or `h3`, kindly change that.

2022-08-19 19:34 UTC, mirouhml commented on index.html
> +        </ul>
- [ ] Good job implementing the icons as a list, what's left to do is please wrap every `img` tag with an `a` tag, because the icons are meant to serve as links to your social media account. 😁

2022-08-19 19:34 UTC, mirouhml commented on index.html
> +        <img class="last-image"  src="mobile-version-images/illustration-header-mobile.png" alt="">
- [ ] Please know that the illustration image should be put as a background image using CSS and not as an element in HTML, you can follow [this guide](https://www.w3schools.com/cssref/pr_background-image.asp) for more information about this. 😁

2022-08-19 19:34 UTC, mirouhml commented on index.html
> +        </div>
- [ ] Please use `flexbox` to align the items in this section, right now it's using the default `block` display. 😁

2022-08-20 14:57 UTC, MaganaAsiati commented
hi, how are you please can you fix linter for stylelint

2022-08-20 15:04 UTC, MaganaAsiati reviewed
# Hi @Adebayo-George 

made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request :negative_squared_cross_mark:

You have submitted a project, but the linter is not passing. Follow [this instruction](https://github.com/microverseinc/linters-config/tree/master/html-css#html--css3-course) to see how to fix the linter automatically 
for your case is  the styling which  not passing you can run 
Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏


<img src="https://media0.giphy.com/media/QvMIzHw30MmMAqvOeo/giphy.gif"/>

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
Cheers and Happy coding!👏👏👏
--------

_Invalid Code Review Request **Does not count** into the code reviews limit._

2022-08-20 18:20 UTC, sumairq approved these changes
### Hi @Adebayo-George  , 

<img src="https://media4.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"/>

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✔️ Good commit history
✔️Linters are passing
✔️Very professional README
✔️Correct Github flow
✔️Descriptive PR
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-22 07:17 UTC, Bondok6 approved these changes
# STATUS: APPROVED :green_circle: :clap: 

## Hi @Adebayo-George , 
Your project is complete!  There is nothing else to say other than... Great job 👏 
Congratulations! 🎉 

TO HIGHLIGHT:

- Your project is professional ✅
- Your repo is professional ✅
- Well structured files ✅
-  Professional README.md file 💯


Now you can merge this branch and move on :1st_place_medal: 
HAPPY CODING AND GOOD LUCK WITH THE COMMING ONES :crossed_fingers: :four_leaf_clover: 

<img src="https://camo.githubusercontent.com/54a5d803a138b5a1a1242a607e4c1192c852cab8c591c1ddcaa33d06b51560f6/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f686c516559335062684833692f67697068792e676966" />


em were simply missed by the previous reviewer and addressing them will really improve your application.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-02 17:41 UTC, merged